feign:
  hystrix:
    enabled: true
server:
  port: 80
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:7776/eureka/
spring:
  application:
    name: pn-hystrix

